---
permalink: api-changes.html 
sidebar: sidebar 
keywords: rest api, api changes, parameters, default values, breaking changes, documentation errors 
summary: 'NetApp continue d"améliorer et de mettre à jour l"API REST ONTAP à chaque nouvelle version majeure du produit. Ces mises à jour peuvent parfois inclure des modifications des appels d"API existants qui perturbent l"accès à la fonctionnalité ONTAP. Il existe également des considérations supplémentaires lors de l"utilisation de l"API ainsi que quelques erreurs dans la documentation.' 
---
= Modifications apportées aux appels de l'API REST ONTAP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
NetApp continue d'améliorer et de mettre à jour l'API REST ONTAP à chaque nouvelle version majeure du produit. Ces mises à jour peuvent parfois inclure des modifications des appels d'API existants qui perturbent l'accès à la fonctionnalité ONTAP. Il existe également des considérations supplémentaires lors de l'utilisation de l'API ainsi que quelques erreurs dans la documentation.



== Modifications apportées aux appels de l'API REST ONTAP existants

Les modifications apportées aux appels d'API REST ONTAP existants, tels que les points de terminaison et les paramètres, peuvent affecter les logiciels qui utilisent l'API. Dans la plupart des situations, selon votre environnement, celles-ci sont considérées comme des _modifications incompatibles_. Vous devez examiner la liste dans le tableau ci-dessous pour déterminer s'il y a un impact sur votre environnement d'automatisation. Chaque entrée inclut le point de terminaison ou la zone d'API concernée, une description de la modification et la version d'ONTAP dans laquelle elle a été introduite.

[cols="40%,50%,10%"]
|===
| Point de terminaison ou zone de l'API | Description du comportement | Version de ONTAP 


| Coffre-fort de clés Azure | Le point de terminaison de l'API REST utilisé pour activer et désactiver Azure Key Vault (AKV) s'exécute désormais de manière asynchrone au lieu de manière synchrone. Cela concerne l'opération POST pour activer AKV et l'opération DELETE pour le désactiver. Les clients utilisant ces appels d'API doivent mettre à jour leur code pour gérer les réponses asynchrones, ce qui implique de vérifier l'état de la tâche au lieu du simple code d'état HTTP. Ce changement impacte principalement les environnements Azure NetApp Files (ANF) qui gèrent les configurations Azure Key Vault via l'API REST ONTAP. | 9.19.1 


| `/security/authentication/duo/groups`
`/security/authentication/duo/profiles` | Le champ *_Links* dans la réponse a été supprimé du double groupe pour ces noeuds finaux. Aucune action ou solution de rechange n'est recommandée au client. Ce champ devrait être ajouté dans une prochaine version de ONTAP. | 9.15.1 
|===


== Considérations supplémentaires relatives à l'utilisation de l'API REST

Outre les modifications perturbatrices ou incompatibles, il existe plusieurs autres considérations lors de l'utilisation de l'API REST ONTAP. Il existe différents types de problèmes, notamment l'introduction de nouveaux appels d'API ou d'appels alternatifs, ainsi que des modifications du traitement interne d'ONTAP. Chaque entrée comprend le point de terminaison ou la zone d'API concernée, une description du comportement et la version d'ONTAP dans laquelle elle a été introduite.

[cols="40%,50%,10%"]
|===
| Point de terminaison ou zone de l'API | Description du comportement | Version de ONTAP 


| `/api/application/containers` | Le point de terminaison utilisé pour créer des conteneurs a été amélioré afin de prendre en charge plusieurs paramètres de configuration de volume auparavant disponibles uniquement via  `/api/storage/volumes`. Cela permet aux clients, notamment ceux utilisant NetApp Trident pour l'orchestration du stockage Kubernetes, de tirer parti de la fonctionnalité de placement équilibré d'ONTAP lors du provisionnement de volumes persistants. Les volumes peuvent être automatiquement répartis sur les nœuds du cluster pour des performances et une utilisation de la capacité optimales. Vous devriez utiliser le point de terminaison mis à jour lors du déploiement d'applications conteneurisées nécessitant un contrôle précis du placement des volumes, des politiques QoS ou de la gestion de la capacité. Ceci est particulièrement utile dans les environnements Kubernetes à grande échelle où l'équilibrage de charge automatique des ressources de stockage est essentiel. | 9.19.1 


| `/api/cluster/licensing/licenses` | Lors de la récupération des informations de licence via l'API REST pour les très grands clusters ONTAP (32 nœuds ou plus), vous pouvez rencontrer des temps de réponse lents. Ce problème affecte les onglets de licences de System Manager et les flux de travail automatisés qui interrogent toutes les licences simultanément. Pour réduire l'impact, vous pouvez récupérer les licences pour des fonctionnalités spécifiques une par une à l'aide de paramètres de requête ou utiliser la CLI avec la commande  `system license show`, au lieu de récupérer toutes les licences en un seul appel API. | 9.19.1 
|===


== Erreurs dans la documentation de référence de l'API REST ONTAP

À mesure que NetApp améliore et met à jour l'API REST d'ONTAP, des erreurs peuvent parfois être introduites dans la documentation de référence en ligne. Ces erreurs peuvent créer de la confusion lors de l'utilisation de l'API, mais n'ont généralement pas d'impact ni ne perturbent votre logiciel ou environnement d'automatisation ONTAP. Vous devriez consulter la liste des erreurs dans le tableau ci-dessous. Cela vous aidera à mieux comprendre et à naviguer dans la documentation de référence de l'API REST d'ONTAP. Chaque entrée inclut le point de terminaison ou la zone de l'API concernée, une description de l'erreur et la version d'ONTAP dans laquelle elle a été introduite.

[cols="40%,50%,10%"]
|===
| Point de terminaison ou zone de l'API | Description de la modification | Version de ONTAP 


| `/storage/quota/reports` | La documentation de l'API REST pour le noeud final indique que *spécificateur* est un champ valide. Toutefois, le spécificateur de quota n'est pas pris en charge avec ce noeud final. Aucune action ou solution de rechange n'est recommandée au client. Ce champ sera supprimé de la documentation de l'API dans une prochaine version de ONTAP. | 9.6 
|===
.Informations associées
link:whats-new.html["Quelles sont les nouveautés de l'API REST de ONTAP"]
