---
settings:
  name: ONTAP Automation
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  langs: fr-fr,us-en,ja-jp,ko-kr,zh-cn,zh-tw,de-de,es-es,it-it
sidebar:
  entries:
  - title: Documentation sur l'automatisation ONTAP
    url: "/index.html"
  - section: rn
  - section: get-started
  - section: rest
  - section: workflows
  - section: manage
  - section: python
  - section: migrate
  - section: reference
  - section: automate
  - section: additional
  - title: Mentions légales
    url: "/legal-notices.html"
homepage:
  tiles:
  - title: Commencez
    links:
    - title: Notes de version
      url: https://library.netapp.com/ecm/ecm_download_file/ECMLP2492508
    - title: Options d'automatisation ONTAP
      url: "/get-started/ontap_automation_options.html"
    - title: Votre premier appel API
      url: "/get-started/first_call.html"
  - title: L'API REST DE ONTAP
    links:
    - title: Détails d'implémentation REST
      url: "/rest/rest_web_services_foundation.html"
    - title: Autres considérations
      url: "/rest/object_references_and_access.html"
    - title: Résumé des ressources REST
      url: "/resources/overview_categories.html"
    - title: Référence API
      url: "/reference/api_reference.html"
  - title: Automatisation
    links:
    - title: Bibliothèque client Python
      url: "/python/overview_pcl.html"
    - title: ONTAP et Ansible
      url: "/automate/ontap_ansible.html"
    - title: Blogs d'automatisation
      url: "/automate/blogs.html"
  - title: Migrer vers l'API REST
    links:
    - title: Désactivation d'ONTAPI
      url: "/migrate/overview.html"
    - title: Mappage ONTAPI vers REST
      url: "/migrate/mapping.html"
    - title: Compteurs de performances
      url: "/migrate/performance-counters.html"
    - title: Articles de blog
      url: "/migrate/blogs.html"
  - title: Connaissances et support
    links:
    - title: Ressources supplémentaires
      url: "/additional/resources.html"
    - title: NetApp DevNet
      url: https://devnet.netapp.com/restapi.php
    - title: Documentation ONTAP 9
      url: https://docs.netapp.com/us-en/ontap/
    - title: Documentation ONTAP Select
      url: https://docs.netapp.com/us-en/ontap-select/
product-family:
  name: ONTAP
  repo: ontap-family
