---
sidebar: sidebar 
permalink: resources/application.html 
keywords: rest, rest api, applications, application resources 
summary: 'Vous pouvez utiliser ces appels d"API pour gérer les ressources de l"application ONTAP.' 
---
= Ressources applicatives dans l'API REST ONTAP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Vous pouvez utiliser ces appels d'API pour gérer les ressources de l'application ONTAP.

.Conteneurs d'application
Vous pouvez utiliser un conteneur d'application pour provisionner un ou plusieurs objets de stockage. Ce type de ressource a été introduit avec ONTAP 9.17.1.

.Snapshots d'applications
Les applications prennent en charge les copies Snapshot, qui peuvent être créées ou restaurées à tout moment. Ce type de ressource a été introduit avec ONTAP 9.6.

.En termes de latence
Les applications ONTAP sont organisées selon les types, notamment les modèles, les applications, les composants et les copies Snapshot. Ce type de ressource a été introduit avec ONTAP 9.6.

.Groupes de cohérence
Un groupe de cohérence est un ensemble de volumes qui sont regroupés au cours de certaines opérations telles que les snapshots. Cette fonctionnalité étend la même cohérence de panne et l'intégrité des données implicite avec les opérations à un seul volume sur un ensemble de volumes. Ce type de ressource a été introduit avec ONTAP 9.10 et mis à jour avec 9.12. Un terminal pour récupérer les données de mesure de la performance et de la capacité a été ajouté à ONTAP 9.13.

.Snapshots de groupes de cohérence
Vous pouvez utiliser ces noeuds finaux pour copier, créer, inventorier et restaurer des instantanés pour un groupe de cohérence. Ce type de ressource a été introduit avec ONTAP 9.10.
