---
sidebar: sidebar 
permalink: resources/ndmp.html 
keywords: ndmp resources 
summary: 'Vous pouvez utiliser ces appels d"API pour gérer les services NDMP.' 
---
= NDMP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Vous pouvez utiliser ces appels d'API pour gérer les services NDMP.

.Mode NDMP
Le mode de fonctionnement NDMP peut être défini au niveau du SVM ou du node. Ce type de ressource a été introduit avec ONTAP 9.7.

.Nœuds NDMP
Vous pouvez gérer la configuration NDMP des nœuds. Ce type de ressource a été introduit avec ONTAP 9.7.

.Sessions NDMP
Vous pouvez récupérer et supprimer les détails d'une session NDMP pour un SVM ou un nœud spécifique. Ce type de ressource a été introduit avec ONTAP 9.7.

.SVM NDMP
On peut gérer la configuration NDMP des SVM. Ce type de ressource a été introduit avec ONTAP 9.7.

.Mots de passe utilisateur SVM NDMP
Vous pouvez générer et récupérer des mots de passe pour un utilisateur NDMP spécifique au sein du contenu de la SVM. Ce type de ressource a été introduit avec l'API REST de ONTAP 9.8 et amélioré avec ONTAP 9.9.
