---
sidebar: sidebar 
permalink: resources/nvme.html 
keywords: nvme resources 
summary: 'Vous pouvez utiliser ces appels d"API pour gérer les ressources prenant en charge NVMe.' 
---
= NVMe
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Vous pouvez utiliser ces appels d'API pour gérer les ressources prenant en charge NVMe (non-volatile Memory Express).

.Connexions Fibre Channel
Les connexions Fibre Channel représentent les connexions formées par les initiateurs Fibre Channel connectés à ONTAP. Ce type de ressource a été introduit avec ONTAP 9.6.

.Espaces de noms
Un namespace NVMe est un ensemble de blocs logiques adressables présentés aux hôtes connectés au SVM via le protocole NVMe over Fabrics. Ce type de ressource a été introduit avec ONTAP 9.6 et mis à jour avec ONTAP 9.8. La prise en charge de l'extraction des données de mesures de performances a été ajoutée avec ONTAP 9.14.

.Interfaces NVMe
Les interfaces NVMe sont les interfaces réseau configurées pour prendre en charge le protocole NVMe over Fabrics (NVMe-of). Ce type de ressource a été introduit avec ONTAP 9.6.

.Services NVMe
Un service NVMe définit les propriétés de la cible du contrôleur NVMe pour une SVM. Ce type de ressource a été introduit avec ONTAP 9.6 et mis à jour avec ONTAP 9.7. La prise en charge de l'extraction des données de mesures de performances a été ajoutée avec ONTAP 9.14.

.Contrôleurs de sous-système NVMe
Les contrôleurs du sous-système NVMe représentent des connexions dynamiques entre les hôtes et une solution de stockage. Ce type de ressource a été introduit avec ONTAP 9.6.

.Mappages de sous-systèmes NVMe
Un mappage de sous-système NVMe est une association d'un namespace NVMe avec un sous-système NVMe. Ce type de ressource a été introduit avec ONTAP 9.6.

.Sous-systèmes NVMe
Un sous-système NVMe conserve l'état de configuration et le contrôle d'accès à l'espace de noms pour un ensemble d'hôtes connectés via NVMe. Ce type de ressource a été introduit avec ONTAP 9.6.
