---
sidebar: sidebar 
permalink: resources/security.html 
keywords: rest, rest api, security, security resources 
summary: Vous pouvez utiliser ces appels d’API pour gérer les paramètres de sécurité du cluster et des SVM. 
---
= Ressources de sécurité de l'API REST ONTAP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Vous pouvez utiliser ces appels d’API pour gérer les paramètres de sécurité du cluster et des SVM.

.Comptes
Il existe un ensemble de comptes utilisateurs pour le cluster et les SVM. Ce type de ressource a été introduit avec ONTAP 9.6.

.Nom du compte
La configuration d'un compte utilisateur évalué. Ce type de ressource a été introduit avec ONTAP 9.6.

.Proxy Active Directory
Vous pouvez administrer les informations de compte SVM au serveur Active Directory. Ce type de ressource a été introduit avec ONTAP 9.7.

.Protection contre les ransomwares
ONTAP détecte les fichiers potentiellement contenant une menace d'attaque par ransomware. Il existe plusieurs catégories de terminaux. Vous pouvez récupérer une liste de ces fichiers suspects et les supprimer d'un volume. Ce type de ressource a été introduit avec ONTAP 9.10.1. La prise en charge de l'affichage de la version et de la mise à jour du paquet anti-ransomware a été ajoutée avec ONTAP 9.16.

.Statistiques d'entropie anti-ransomware
Des statistiques d'entropie détaillées sont disponibles pour le fonctionnement de la fonctionnalité Autonomous Ransomware Protection (ARP). Ce type de ressource a été ajouté avec ONTAP 9.17.1.

.Audit
Les paramètres qui déterminent ce qui est consigné dans les fichiers journaux d'audit. Ce type de ressource a été introduit avec ONTAP 9.6.

.Destinations d'audit
Ces paramètres contrôlent la façon dont les informations du journal d'audit sont transférées vers des systèmes distants ou des serveurs splunk. Ce type de ressource a été introduit avec ONTAP 9.6.

.Messages d'audit
Vous pouvez récupérer les messages du journal d'audit. Ce type de ressource a été introduit avec ONTAP 9.6.

.KMS AWS
Amazon Web Services inclut un service de gestion des clés qui fournit un stockage sécurisé pour les clés et d'autres secrets. Vous pouvez accéder à ce service via l'API REST pour permettre à ONTAP de stocker ses clés de chiffrement en toute sécurité dans le cloud. En outre, vous pouvez créer et lister les clés d'authentification utilisées par NetApp Storage Encryption. Cette prise en charge a été récemment prise en charge d'ONTAP 9.12.

.Coffre-fort de clés Azure
Cet ensemble d'appels d'API vous permet d'utiliser le coffre-fort de clés Azure pour stocker les clés de cryptage ONTAP. Ce type de ressource est nouveau avec ONTAP 9.8.

.Barbican KMS
La prise en charge du gestionnaire de clés OpenStack Barbican a été ajoutée pour gérer les clés de chiffrement de volumes NetApp (NVE). Ce type de ressource a été ajouté avec ONTAP 9.17.1.

.Certificats
Les appels API peuvent être utilisés pour installer, afficher et supprimer des certificats utilisés par ONTAP. Ce type de ressource a été introduit avec ONTAP 9.7.

.Duo Cisco
Duo fournit une authentification à deux facteurs pour les connexions SSH. Vous pouvez configurer Duo pour qu'il fonctionne au niveau du cluster ONTAP ou du SVM. Ce type de ressource a été introduit avec ONTAP 9.14.

.sécurité du réseau de cluster
Vous pouvez récupérer et mettre à jour la configuration de sécurité du réseau du cluster, y compris les certificats. Ce type de ressource a été introduit avec ONTAP 9.18.

.Sécurité du cluster
Vous pouvez récupérer des informations relatives à la sécurité au niveau du cluster et mettre à jour certains paramètres. Ce type de ressource a été introduit avec ONTAP 9.7 et mis à jour avec ONTAP 9.8.

.Rôles externes
Un rôle externe est défini dans un fournisseur d'identification OAUTH 2.0. Vous pouvez créer et gérer des relations de mappage entre ces rôles externes et les rôles ONTAP. Ce type de ressource a été introduit avec ONTAP 9.16.

.KMS GCP
Cet ensemble d'appels API vous permet d'utiliser le service de gestion des clés Google Cloud Platform pour stocker et gérer les clés de chiffrement ONTAP. Ce type de ressource a été initialement introduit avec l'API REST de ONTAP 9.8. Cependant, cette fonctionnalité a été remaniée et est considérée comme nouvelle, avec de nouveaux types de ressources, dans ONTAP 9.9.

.Groupes
Vous pouvez administrer des configurations de groupe, y compris des groupes représentés par des UUID. Ce type de ressource a été introduit avec ONTAP 9.16.

.Mappages de rôles de groupe
Vous pouvez créer et gérer des relations de mappage entre les groupes et les rôles. Ce type de ressource a été introduit avec ONTAP 9.16.

.Sécurité du réseau HA
Vous pouvez récupérer et mettre à jour la configuration de sécurité du réseau HA. Ce type de ressource a été introduit avec ONTAP 9.18.

.IPSec
IPSec (Internet Protocol Security) est une suite de protocoles assurant la sécurité entre deux points de terminaison via un réseau IP sous-jacent. Ce type de ressource est nouveau avec ONTAP 9.8.

.Certificats AC IPsec
Vous pouvez ajouter, supprimer et récupérer des certificats d'autorité de certification IPSec. Ce type de ressource est nouveau avec ONTAP 9.10.

.Stratégies IPsec
Vous pouvez utiliser cet ensemble d'appels API pour gérer les stratégies en vigueur pour un déploiement IPSec. Ce type de ressource est nouveau avec ONTAP 9.8.

.Associations de sécurité IPsec
Vous pouvez utiliser cet ensemble d'appels API pour gérer les associations de sécurité en vigueur pour un déploiement IPSec. Ce type de ressource est nouveau avec ONTAP 9.8.

.Élévation des privilèges juste à temps (JIT)
L'élévation des privilèges (JIT) est une amélioration du contrôle d'accès basé sur les rôles (RBAC). Les administrateurs de cluster peuvent demander une élévation temporaire vers un rôle existant. Ce type de ressource a été ajouté avec ONTAP 9.17.1.

.Configurations du gestionnaire de clés
Ces noeuds finaux vous permettent de récupérer et de mettre à jour les configurations des gestionnaires de clés. Ce type de ressource est nouveau avec ONTAP 9.10.

.Gestionnaires clés
Un gestionnaire de clés permet aux modules clients de ONTAP de stocker des clés en toute sécurité. Ce type de ressource a été introduit avec ONTAP 9.6 et mis à jour pour ONTAP 9.7. Une autre mise à jour a été effectuée avec ONTAP 9.12 pour prendre en charge les clés d'authentification. Une fonctionnalité de restauration a été ajoutée à ONTAP 9.13.

.Magasins clés
Un magasin de clés décrit le type d'un gestionnaire de clés. Ce type de ressource est nouveau avec ONTAP 9.10. Des terminaux supplémentaires prenant en charge le contrôle renforcé ont été ajoutés avec ONTAP 9.14.

.Authentification LDAP
Ces appels d'API sont utilisés pour récupérer et gérer la configuration du serveur LDAP du cluster. Ce type de ressource a été introduit avec ONTAP 9.6.

.Messages de connexion
Permet d'afficher et de gérer les messages de connexion utilisés par ONTAP. Ce type de ressource a été introduit avec ONTAP 9.6.

.Vérification par plusieurs administrateurs
La fonction de vérification administrateur multiple fournit une structure d'autorisation flexible pour protéger l'accès aux commandes ou opérations ONTAP. Dix-sept nouveaux points finaux prennent en charge la définition, la demande et l'approbation de l'accès dans les domaines suivants :

* Règles
* Requêtes
* Groupes d'approbation


En autorisant plusieurs administrateurs à approuver l'accès, il améliore la sécurité de vos environnements ONTAP et IT. Ces types de ressources ont été introduits avec ONTAP 9.11.

.Authentification NIS
Ces paramètres sont utilisés pour récupérer et gérer la configuration du serveur NIS du cluster. Ce type de ressource a été introduit avec ONTAP 9.6.

.OAuth 2.0
L'autorisation ouverte (OAuth 2.0) est une structure basée sur un jeton qui peut être utilisée pour restreindre l'accès à vos ressources de stockage ONTAP. Vous pouvez l'utiliser avec des clients qui accèdent à ONTAP via l'API REST. Ce type de ressource a été introduit avec ONTAP 9.14. Il a été amélioré avec ONTAP 9.16 grâce à la prise en charge du serveur d'autorisation Microsoft Entra ID (anciennement Azure AD) avec des demandes OAuth 2.0 standard. En outre, les demandes de groupe standard Entra ID basées sur des valeurs de style UUID sont prises en charge via de nouvelles fonctionnalités de mappage de groupe et de rôle. Une nouvelle fonction de mappage de rôle externe a également été introduite. Voir aussi *rôles externes*, *groupes* et *mappages de rôles de groupe*.

.Authentification par mot de passe
Cela inclut l'appel API utilisé pour modifier le mot de passe d'un compte utilisateur. Ce type de ressource a été introduit avec ONTAP 9.6.

.Privilèges pour une instance de rôle
Gérer les privilèges d'un rôle spécifique. Ce type de ressource a été introduit avec ONTAP 9.6.

.Authentification par clé publique
Vous pouvez utiliser ces appels API pour configurer les clés publiques des comptes utilisateur. Ce type de ressource a été introduit avec ONTAP 9.7.

.Rôles
Les rôles permettent d'attribuer des privilèges aux comptes d'utilisateur. Ce type de ressource a été introduit avec ONTAP 9.6.

.Instance de rôles
Instance spécifique d'un rôle. Ce type de ressource a été introduit avec ONTAP 9.6.

.Fournisseur de services SAML
Vous pouvez afficher et gérer la configuration du fournisseur de services SAML. Ce type de ressource a été introduit avec ONTAP 9.6.

.Métadonnées par défaut du fournisseur de services SAML
Vous pouvez gérer la configuration des métadonnées SAML par défaut d'un cluster. Ce type de ressource a été ajouté avec ONTAP 9.17.1.

.SSH
Ces appels vous permettent de définir la configuration SSH. Ce type de ressource a été introduit avec ONTAP 9.7.

.SVM SSH
Ces terminaux vous permettent d'extraire la configuration de sécurité SSH pour tous les SVM. Ce type de ressource a été introduit avec ONTAP 9.10.

.TOTPS
Vous pouvez utiliser l'API REST pour configurer les profils TOTP (Time-based unique password) pour les comptes qui se connectent et accèdent à ONTAP à l'aide de SSH. Ce type de ressource a été introduit avec ONTAP 9.13.

.Authentification Web
L'authentification Web (WebAuthn) est une norme Web pour l'authentification sécurisée des utilisateurs basée sur la cryptographie de clé publique. Avec ONTAP, il prend en charge l'administration des appels de demandes de soutien résistants au phishing via System Manager et l'API REST de ONTAP. Cette fonctionnalité a été ajoutée avec ONTAP 9.16.
