---
sidebar: sidebar 
permalink: migrate/blogs.html 
keywords: blogs, blog articles 
summary: 'Plusieurs articles de blog sont disponibles pour vous aider à mieux comprendre comment migrer de ONTAPI vers l"API REST ONTAP.' 
---
= Blogs sur la migration vers l'API REST de ONTAP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Plusieurs articles de blog sont disponibles pour vous aider à mieux comprendre comment migrer de ONTAPI vers l'API REST ONTAP.

.Mappage ONTAPI vers REST
NetApp prend en charge le transfert de l'API ONTAPI propriétaire vers l'API REST ONTAP via la documentation de mappage.

https://netapp.io/2020/12/17/ontapi-to-rest-mapping/["netapp.io/2020/12/17/ontapi-to-rest-mapping"^]

.Transformez votre automatisation en API REST ONTAP à partir de ONTAPI
Plusieurs technologies sont disponibles pour vous aider à transformer votre environnement d'automatisation ONTAP basé sur l'API REST.

https://www.netapp.com/blog/transform-automation-ontap-rest-api/["www.netapp.com/blog/transform-automation-ontap-rest-api"^]

.Utilisation de la passerelle CLI privée avec l'API REST de ONTAP
Pour faciliter la transition des utilisateurs de l'interface de ligne de commande et de ONTAP vers l'API REST ONTAP, ONTAP fournit un terminal d'API REST privé pouvant être utilisé pour accéder à n'importe quelle commande CLI.

https://netapp.io/2020/11/09/private-cli-passthrough-ontap-rest-api/["https://netapp.io/2020/11/09/private-cli-passthrough-ontap-rest-api"^]

.Transition depuis ONTAPI à l'aide de l'outil de reporting d'utilisation ONTAPI
NetApp propose un outil qui aide les clients et les partenaires à passer à l'API REST ONTAP.

https://netapp.io/2022/03/21/transitioning-from-ontapizapi-using-ontapi-usage-reporting-tool/["netapp.io/2022/03/21/transition-from-ontapizapi-using-ontapi-reporting-utilisation-reporting"^]
