---
sidebar: sidebar 
permalink: migrate/software.html 
keywords:  
summary:  
---
= Outils et logiciels
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
NetApp fournit des exemples de scripts Python et d'autres logiciels associés pour prendre en charge votre migration d'ONTAPI vers l'API REST ONTAP. Les plus importants de ces échantillons sont décrits ci-dessous.


NOTE: Tous les exemples de code Python sont disponibles sur le https://github.com/NetApp/ontap-rest-python["NetApp ONTAP REST Python"^] Référentiel GitHub.

.Outil de reporting sur l'utilisation de ONTAPI
L'outil de reporting sur l'utilisation d'ONTAP est conçu pour aider les services professionnels, les clients et les partenaires de NetApp à identifier l'utilisation d'ONTAP dans leur environnement ONTAP. Des scripts sont fournis pour trois cas d'utilisation différents, comme décrit dans le tableau ci-dessous.

[cols="20,80"]
|===
| Script | Description 


| apache_scraper.py | Un utilitaire de récupération des journaux Apache pour rechercher les appels ONTAPI émis sur les nœuds ONTAP 


| session_stats.py | Un script CLI pour récupérer les données statistiques de session à partir de ONTAP 


| zapi_to_rest.py | Script permettant d'extraire les détails REST des appels et attributs ONTAPI transmis 
|===
Voir https://github.com/NetApp/ontap-rest-python/tree/master/ONTAPI-Usage-Reporting-Tool["Outil de reporting sur l'utilisation de ONTAPI"^] pour en savoir plus.

.Passerelle CLI privée
L'API REST offre une large couverture des fonctionnalités et des installations disponibles avec ONTAP. Cependant, il peut y avoir des cas où l'accès direct à l'interface de ligne de commandes de ONTAP via l'API REST peut être utile.

Pour une introduction à cette fonctionnalité, voir link:../rest/access_ontap_cli.html["Accès à l'interface de ligne de commandes de ONTAP via l'API REST"]. Pour les échantillons Python, voir https://github.com/NetApp/ontap-rest-python/tree/master/examples/rest_api/cli_passthrough_samples["Exemples de passage CLI REST"^].

.Bibliothèque client Python
La bibliothèque cliente Python est un package que vous pouvez installer et utiliser pour accéder à l'API REST ONTAP avec Python. Elle vous permet de développer rapidement un code robuste pour l'automatisation de vos déploiements ONTAP.

Pour une introduction à la bibliothèque cliente Python, reportez-vous à la section link:../python/overview_pcl.html["Présentation de la bibliothèque client Python"]. Pour les échantillons Python, voir https://github.com/NetApp/ontap-rest-python/tree/master/examples/python_client_library["Exemples de bibliothèques clientes Python"^].
