---
sidebar: sidebar 
permalink: migrate/software.html 
keywords:  
summary:  
---
= Outils et logiciels
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
NetApp fournit des exemples de scripts Python et d'autres logiciels associés pour prendre en charge votre migration d'ONTAPI vers l'API REST ONTAP. Les plus importants de ces échantillons sont décrits ci-dessous.


NOTE: Tous les exemples de code Python sont disponibles dans le https://github.com/NetApp/ontap-rest-python["NetApp ONTAP REST Python"^] référentiel GitHub. Vous devez également consulter les ressources disponibles dans link:../additional/learn_more.html["En savoir plus sur l'API REST ONTAP"].



== Outil de reporting sur l'utilisation de ONTAPI

L'outil de reporting sur l'utilisation d'ONTAP est conçu pour aider les services professionnels, les clients et les partenaires de NetApp à identifier l'utilisation d'ONTAP dans leur environnement ONTAP. Des scripts sont fournis pour trois cas d'utilisation différents, comme décrit dans le tableau ci-dessous.

[cols="20,80"]
|===
| Script | Description 


| apache_scraper.py | Un utilitaire de récupération des journaux Apache pour rechercher les appels ONTAPI émis sur les nœuds ONTAP 


| session_stats.py | Un script CLI pour récupérer les données statistiques de session à partir de ONTAP 


| zapi_to_rest.py | Script permettant d'extraire les détails REST des appels et attributs ONTAPI transmis 
|===
Vous pouvez accéder au https://github.com/NetApp/ontap-rest-python/tree/master/ONTAPI-Usage-Reporting-Tool["Outil de reporting sur l'utilisation de ONTAPI"^] pour commencer. Voir aussi a https://www.youtube.com/watch?v=gJSWerW9S7o["Démo"^] à propos de l'outil de création de rapports et comment l'utiliser.



== Passerelle CLI privée

L'API REST offre une large couverture des fonctionnalités et des installations disponibles avec ONTAP. Cependant, il peut y avoir des cas où l'accès direct à l'interface de ligne de commandes de ONTAP via l'API REST peut être utile.

Pour une introduction à cette fonctionnalité, voir link:../rest/access_ontap_cli.html["Accès à l'interface de ligne de commandes de ONTAP via l'API REST"]. Pour les échantillons Python, voir https://github.com/NetApp/ontap-rest-python/tree/master/examples/rest_api/cli_passthrough_samples["Exemples de passage CLI REST"^].



== Bibliothèque client Python

La bibliothèque cliente Python est un package que vous pouvez installer et utiliser pour accéder à l'API REST ONTAP avec Python. Elle vous permet de développer rapidement un code robuste pour l'automatisation de vos déploiements ONTAP. Pour en savoir plus sur la bibliothèque de clients Python, reportez-vous à la section link:../python/learn-about-pcl.html["Bibliothèque client Python"].



== Kit ONTAP PowerShell

Le kit NetApp.ONTAP PowerShell renforce votre environnement PowerShell local avec un module qui comprend plus de 2,400 cmdlets. Il vous permet de développer rapidement du code pour votre hôte Windows afin d'automatiser les déploiements ONTAP. Pour plus d'informations, voir link:../pstk/overview_pstk.html["Présentation du kit d'outils PowerShell"].
