---
sidebar: sidebar 
permalink: additional/resources.html 
keywords: more information, additional resources 
summary: 'Il existe plusieurs ressources supplémentaires qui vous aideront à obtenir de l"aide et à trouver plus d"informations sur l"automatisation du déploiement et de l"administration de vos systèmes de stockage ONTAP.' 
---
= Ressources supplémentaires
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Plusieurs ressources supplémentaires sont disponibles pour vous aider à automatiser le déploiement et l'administration de vos systèmes de stockage ONTAP.



== Ressources ONTAP 9

* Fournit de la documentation relative à la gamme de produits ONTAP 9.
+
https://docs.netapp.com/us-en/ontap-family/["Documentation produit sur ONTAP 9"^]

* Notes de version de ONTAP 9 avec des informations sur la version actuelle.
+
https://library.netapp.com/ecm/ecm_download_file/ECMLP2492508["Notes de version de ONTAP"^]

* Comprend de la documentation et d'autres liens utiles dont vous avez besoin pour planifier, administrer et soutenir ONTAP 9.
+
https://www.netapp.com/us/documentation/ontap-and-oncommand-system-manager.aspx["Ressources ONTAP et ONTAP System Manager"^]

* Accédez aux notes de version et à toute autre documentation relative aux versions précédentes de ONTAP.
+
https://mysupport.netapp.com/documentation/productlibrary/index.html?productID=62286["Bibliothèque de produits ONTAP 9"^]





== Ressources du développeur ONTAP 9

* Il aide à la mise en route avec Ansible dans un environnement DevOps.
+
https://www.netapp.com/devops-solutions/ansible/["Solutions DevOps NetApp Ansible"^]

* Fournit les appels de clé ONTAPI et un mappage avec les appels d'API REST équivalents. Sélectionnez la version ONTAP appropriée.
+
link:../migrate/mapping.html["Mappage de l'API REST avec ONTAPI"]

* Package de bibliothèque client NetApp Python à PyPI.
+
https://pypi.org/project/netapp-ontap["PyPI : NetApp ONTAP"^]

* Documentation relative à la bibliothèque client NetApp Python.
+
https://library.netapp.com/ecmdocs/ECMLP2886776/html/index.html["Documentation NetApp PCL pour 9.14.1"^]

* Fournit les ressources et la documentation nécessaires à l'utilisation de l'API REST ONTAP.
+
https://devnet.netapp.com/restapi.php["Réseau de développeurs NetApp : API RESTful ONTAP"^]





== Articles de blog

* La méthode de passage de l'interface de ligne de commande fournit une technique pour l'exécution des commandes de l'interface de ligne de commande ONTAP à l'aide de l'API REST.
+
https://netapp.io/2020/11/09/private-cli-passthrough-ontap-rest-api["Utilisation de la passerelle CLI privée avec l'API REST de ONTAP"^]

* Si vous ne connaissez pas encore Ansible pour l'automatisation d'ONTAP, c'est un bon point de départ.
+
https://netapp.io/2018/10/08/getting-started-with-netapp-and-ansible-install-ansible["Mise en route avec NetApp et Ansible : installation d'Ansible"^]





== Vidéos

* Une bonne introduction à la bibliothèque client NetApp Python et comment commencer à écrire du code à l'aide de la bibliothèque.
+
https://www.youtube.com/watch?v=Wws3SB5d9Ss["Mise en route avec la bibliothèque client Python NetApp ONTAP"^]

* Cette vidéo est également disponible sur NetApp TV à l'adresse link:https://tv.netapp.com/detail/video/6217195551001["Modules certifiés Ansible"^].
+
video::L5DZBV_Sg9E[youtube,width=848,height=480]
* Découvrez les modules certifiés Ansible.
+
video::ZlmQ5IuVZD8[youtube,width=848,height=480]




== Ressources NetApp

* Accédez aux outils de dépannage, à la documentation et à l'assistance technique.
+
https://mysupport.netapp.com/["Support NetApp"^]

* Consultez les informations sur les exigences et la compatibilité relatives à l'utilisation d'ONTAP 9 et de l'API REST de ONTAP.
+
https://mysupport.netapp.com/matrix["Matrice d'interopérabilité NetApp"^]

* Accédez à des rapports techniques, à des livres blancs et à d'autres documents.
+
http://www.netapp.com/us/library/index.aspx["Bibliothèque NetApp de rapports techniques et de livres blancs"^]


