---
sidebar: sidebar 
permalink: reference/api_reference.html 
keywords: reference, API reference, ONTAP API documentation 
summary: 'La référence de l"API contient des détails sur tous les appels de l"API REST de ONTAP, y compris les méthodes HTTP, les paramètres d"entrée et les réponses. Cette référence complète est utile lors du développement d"applications d"automatisation à l"aide de l"API REST.' 
---
= Référence API
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
La référence de l'API contient des détails sur tous les appels de l'API REST de ONTAP, y compris les méthodes HTTP, les paramètres d'entrée et les réponses. Cette référence complète est utile lors du développement d'applications d'automatisation à l'aide de l'API REST.


NOTE: Vous pouvez accéder au contenu de référence en ligne de votre système ONTAP local ou à une copie statique de la documentation gérée par NetApp.



== Accédez à la page de documentation de l'API ONTAP

[role="lead"]
Vous pouvez accéder à la page de documentation en ligne de l'API ONTAP sur votre système ONTAP local.

.Avant de commencer
Vous devez disposer des éléments suivants :

* Adresse IP ou nom d'hôte de la LIF de gestion du cluster ONTAP
* Nom d'utilisateur et mot de passe d'un compte autorisé à accéder à l'API REST de ONTAP


.Étapes
. Saisissez l'URL dans votre navigateur et appuyez sur *entrée* :
+
`https://<ip_address>/docs/api`

. Connectez-vous à l'aide du compte ONTAP.
+
La page de documentation de l'API ONTAP s'affiche avec les appels API organisés dans les principales catégories de ressources en bas.

. Comme exemple d'appel d'API individuel, faites défiler jusqu'à la catégorie *cluster* et cliquez sur *LIRE /cluster*.




== Accédez à une copie de la documentation de référence de l'API REST de ONTAP

[role="lead"]
Vous pouvez accéder à une copie de la documentation de référence de l'API REST de ONTAP via les liens ci-dessous. La documentation de référence de l'API est gérée par la version d'ONTAP.

* https://docs.netapp.com/us-en/ontap-restapi/["ONTAP 9.14.1"^]
* https://docs.netapp.com/us-en/ontap-restapi-9131/["ONTAP 9.13.1"^]
* https://docs.netapp.com/us-en/ontap-restapi-9121/["ONTAP 9.12.1"^]
* https://docs.netapp.com/us-en/ontap-restapi-9111/["ONTAP 9.11.1"^]
* https://docs.netapp.com/us-en/ontap-restapi-9101/["ONTAP 9.10.1"^]
* https://docs.netapp.com/us-en/ontap-restapi-991/["ONTAP 9.9.1"^]
* https://docs.netapp.com/us-en/ontap-restapi-98/["ONTAP 9.8"^]
* https://docs.netapp.com/us-en/ontap-restapi-97/["ONTAP 9.7"^]
* https://docs.netapp.com/us-en/ontap-restapi-96/["ONTAP 9.6"^]


.Informations associées
https://devnet.netapp.com/restapi.php["NetApp DevNet : API REST de ONTAP"^]
