---
sidebar: sidebar 
permalink: workflows/wf_1_update_cluster_contact.html 
keywords: workflow 
summary: 'Ce workflow met à jour les informations de contact sur le cluster. Comme la requête est traitée de manière asynchrone, elle indique également comment déterminer si la tâche d"arrière-plan s"exécute correctement.' 
---
= Workflow 1 : mettez à jour le contact du cluster et vérifiez l'état du travail
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Ce workflow met à jour les informations de contact sur le cluster. Comme la requête est traitée de manière asynchrone, elle indique également comment déterminer si la tâche d'arrière-plan s'exécute correctement.



=== 1. Mettre à jour les coordonnées du cluster

Vous pouvez lancer un appel d'API pour mettre à jour les coordonnées. Comme la requête s'exécute de manière asynchrone, vous devez confirmer le succès du travail associé.

|===
| Catégorie | Méthode HTTP | Chemin 


| Cluster | CORRECTIF | /cluster 
|===
.Type de traitement
Asynchrone

.Gondolage
[source, curl]
----
curl -X PATCH -H 'Content-Type: application/json' -u admin:password -k -d @step01 'https://10.222.81.101/api/cluster'
{
  "contact": "support@company-demo.com"
}
----
.Sortie JSON
Un objet de travail avec l'identifiant associé est renvoyé.

[source, json]
----
{ "job": {
  "uuid": "d877f5bb-3aa7-11e9-b6c6-005056a78c89",
  "_links": {
    "self": {
      "href": "/api/cluster/jobs/d877f5bb-3aa7-11e9-b6c6-005056a78c89"
    }
  }
  }
}
----


=== 2. Récupérez l'état du travail

Vous devez récupérer l'état du travail pour déterminer si la demande asynchrone a bien été effectuée.

|===
| Catégorie | Méthode HTTP | Chemin 


| Cluster | OBTENEZ | /cluster/tâches/{uuid} 
|===
.Type de traitement
Synchrone

.Gondolage
[source, curl]
----
curl -X GET -H 'Content-Type: application/json' -u admin:password -k 'https:// 10.222.81.101/api/cluster/jobs/*uuid*'
----
.Sortie
Un objet de travail avec l'état et d'autres champs est renvoyé.

[source, json]
----
{
  "uuid": "d877f5bb-3aa7-11e9-b6c6-005056a78c89",
  "description": "PATCH /api/cluster",
  "state": "success",
  "message": "success",
  "code": 0,
  "_links": {
    "self": {
      "href": "/api/cluster/jobs/d877f5bb-3aa7-11e9-b6c6-005056a78c89"
    }
  }
}
----