---
sidebar: sidebar 
permalink: workflows/wf_cls_update_contact.html 
keywords: workflow, update cluster, cluster contact 
summary: 'Vous pouvez mettre à jour les coordonnées d"un cluster. Étant donné que la demande est traitée de manière asynchrone, vous devez également déterminer si la tâche d"arrière-plan associée s"est terminée avec succès.' 
---
= Mettre à jour le contact du cluster
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Vous pouvez mettre à jour les coordonnées d'un cluster. Étant donné que la demande est traitée de manière asynchrone, vous devez également déterminer si la tâche d'arrière-plan associée s'est terminée avec succès.



== Étape 1 : mettez à jour les coordonnées du cluster

Vous pouvez émettre un appel d'API pour mettre à jour les informations de contact du cluster.

.Méthode HTTP et noeud final
Cet appel d'API REST utilise la méthode et le point de terminaison suivants.

[cols="25,75"]
|===
| Méthode HTTP | Chemin 


| CORRECTIF | /api/cluster 
|===
.Type de traitement
Asynchrone

.Exemple de boucle
[source, curl]
----
curl --request PATCH \
--location "https://$FQDN_IP/api/cluster" \
--include \
--header "Content-Type: application/json" \
--header "Accept: */*" \
--header "Authorization: Basic $BASIC_AUTH" \
--data @JSONinput
----
.Exemple d'entrée JSON
[source, json]
----
{
  "contact": "support@company-demo.com"
}
----
.Exemple de sortie JSON
Un objet de travail est renvoyé. Vous devez enregistrer l'identifiant du travail pour l'utiliser à l'étape suivante.

[listing]
----
{ "job": {
    "uuid": "d877f5bb-3aa7-11e9-b6c6-005056a78c89",
    "_links": {
      "self": {
        "href": "/api/cluster/jobs/d877f5bb-3aa7-11e9-b6c6-005056a78c89"
      }
    }
  }
}
----


== Étape 2 : récupération de l'état du travail

Exécutez le flux de travail link:../workflows/wf_jobs_get_job.html["Obtenir l'instance de travail"] et confirmez le `state` la valeur est `success`.



== Étape 3 : confirmez les coordonnées du cluster

Exécutez le flux de travail link:../workflows/wf_cls_get_cluster.html["Obtenez la configuration du cluster"]. Vous devez définir le `fields` interroger le paramètre sur `contact`.
