---
sidebar: sidebar 
permalink: workflows/wf_nas_fs_apply_permissions.html 
keywords: nas, file security, sacl, dacl, permissions, apply permissions 
summary: Vous pouvez appliquer un nouveau descripteur de sécurité à un fichier ou dossier spécifique. 
---
= Appliquer de nouvelles autorisations à un fichier
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Vous pouvez appliquer un nouveau descripteur de sécurité à un fichier ou dossier spécifique.



== Étape 1 : appliquez les nouvelles autorisations

.Méthode HTTP et noeud final
Cet appel d'API REST utilise la méthode et le point de terminaison suivants.

[cols="25,75"]
|===
| Méthode HTTP | Chemin 


| POST | /api/protocoles/sécurité-fichier/permissions/{svm.uuid}/{path} 
|===
.Type de traitement
Asynchrone

.Paramètres d'entrée supplémentaires pour les exemples de boucles
Outre les paramètres communs à tous les appels API REST, les paramètres suivants sont également utilisés dans l'exemple curl de cette étape.

[cols="25,10,10,55"]
|===
| Paramètre | Type | Obligatoire | Description 


| $SVM_ID | Chemin | Oui. | Il s'agit de l'UUID du SVM contenant le fichier. 


| $FILE_PATH | Chemin | Oui. | Il s'agit du chemin d'accès au fichier ou au dossier. 
|===
.Exemple de boucle
[source, curl]
----
curl --request POST --location "https://$FQDN_IP/api/protocols/file-security/permissions/$SVM_ID/$FILE_PATH?return_timeout=0" --include --header "Accept */*" --header "Authorization: Basic $BASIC_AUTH" --data '{ \"acls\": [ { \"access\": \"access_allow\", \"advanced_rights\": { \"append_data\": true, \"delete\": true, \"delete_child\": true, \"execute_file\": true, \"full_control\": true, \"read_attr\": true, \"read_data\": true, \"read_ea\": true, \"read_perm\": true, \"write_attr\": true, \"write_data\": true, \"write_ea\": true, \"write_owner\": true, \"write_perm\": true }, \"apply_to\": { \"files\": true, \"sub_folders\": true, \"this_folder\": true }, \"user\": \"administrator\" } ], \"control_flags\": \"32788\", \"group\": \"S-1-5-21-2233347455-2266964949-1780268902-69700\", \"ignore_paths\": [ \"/parent/child2\" ], \"owner\": \"S-1-5-21-2233347455-2266964949-1780268902-69304\", \"propagation_mode\": \"propagate\"}'
----
.Exemple de sortie JSON
[listing]
----
{
  "job": {
    "uuid": "3015c294-5bbc-11eb-9c4e-0050568e8682",
    "_links": {
      "self": {
        "href": "/api/cluster/jobs/3015c294-5bbc-11eb-9c4e-0050568e8682"
      }
    }
  }
}
----


== Étape 2 : récupération de l'état du travail

Exécutez le flux de travail link:../workflows/wf_jobs_get_job.html["Obtenir l'instance de travail"] et confirmez le `state` la valeur est `success`.
