---
sidebar: sidebar 
permalink: workflows/wf_nas_fs_update_sd.html 
keywords: nas, file security, security descriptor, sd, update security descriptor 
summary: Vous pouvez mettre à jour un descripteur de sécurité spécifique dans un fichier ou un dossier spécifique, y compris les indicateurs de propriétaire, de groupe ou de contrôle principal. 
---
= Mettez à jour les informations du descripteur de sécurité
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Vous pouvez mettre à jour un descripteur de sécurité spécifique dans un fichier ou un dossier spécifique, y compris les indicateurs de propriétaire, de groupe ou de contrôle principal.



== Étape 1 : mettez à jour le descripteur de sécurité

.Méthode HTTP et noeud final
Cet appel d'API REST utilise la méthode et le point de terminaison suivants.

[cols="25,75"]
|===
| Méthode HTTP | Chemin 


| CORRECTIF | /api/protocoles/sécurité-fichier/permissions/{svm.uuid}/{path} 
|===
.Type de traitement
Asynchrone

.Paramètres d'entrée supplémentaires pour les exemples de boucles
Outre les paramètres communs à tous les appels API REST, les paramètres suivants sont également utilisés dans l'exemple curl de cette étape.

[cols="25,10,10,55"]
|===
| Paramètre | Type | Obligatoire | Description 


| $SVM_ID | Chemin | Oui. | Il s'agit de l'UUID du SVM contenant le fichier. 


| $FILE_PATH | Chemin | Oui. | Il s'agit du chemin d'accès au fichier ou au dossier. 
|===
.Exemple de boucle
[source, curl]
----
curl --request POST --location "https://$FQDN_IP/api/protocols/file-security/permissions/$SVM_ID/$FILE_PATH?return_timeout=0" --include --header "Accept */*" --header "Authorization: Basic $BASIC_AUTH" --data '{ \"control_flags\": \"32788\", \"group\": \"everyone\", \"owner\": \"user1\"}'
----
.Exemple de sortie JSON
[listing]
----
{
  "job": {
    "uuid": "6f89e612-5bbd-11eb-9c4e-0050568e8682",
    "_links": {
      "self": {
        "href": "/api/cluster/jobs/6f89e612-5bbd-11eb-9c4e-0050568e8682"
      }
    }
  }
}
----


== Étape 2 : récupération de l'état du travail

Exécutez le flux de travail link:../workflows/wf_jobs_get_job.html["Obtenir l'instance de travail"] et confirmez le `state` la valeur est `success`.
