---
sidebar: sidebar 
permalink: workflows/wf_nas_fs_get_permissions.html 
keywords: nas, file security, effective permissions 
summary: Vous pouvez récupérer les autorisations effectives actuelles pour un fichier ou un dossier spécifique. 
---
= Obtenez les autorisations efficaces pour un fichier à l'aide de l'API REST ONTAP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Vous pouvez récupérer les autorisations effectives actuelles pour un fichier ou un dossier spécifique.

.Méthode HTTP et noeud final
Cet appel d'API REST utilise la méthode et le point de terminaison suivants.

[cols="25,75"]
|===
| Méthode HTTP | Chemin 


| OBTENEZ | /api/protocoles/sécurité-fichier/autorisations-effectives/{svm.uuid}/{path} 
|===
.Type de traitement
Synchrone

.Paramètres d'entrée supplémentaires pour les exemples de boucles
Outre les paramètres communs à tous les appels API REST, les paramètres suivants sont également utilisés dans l'exemple curl de cette étape.

[cols="25,10,10,55"]
|===
| Paramètre | Type | Obligatoire | Description 


| $SVM_ID | Chemin | Oui. | Il s'agit de l'UUID du SVM contenant le fichier. 


| $FILE_PATH | Chemin | Oui. | Il s'agit du chemin d'accès au fichier ou au dossier. 
|===
.Exemple de boucle
[source, curl]
----
curl --request GET \
--location "https://$FQDN_IP/api/protocols/file-security/effective-permissions/$SVM_ID/$FILE_PATH" \
--include \
--header "Accept: */*" \
--header "Authorization: Basic $BASIC_AUTH"
----
.Exemple de sortie JSON
[listing]
----
{
  "svm": {
    "uuid": "cf5f271a-1beb-11ea-8fad-005056bb645e",
    "name": "vs1"
  },
  "user": "administrator",
  "type": "windows",
  "path": "/",
  "share": {
    "path": "/"
  },
  "file_permission": [
    "read",
    "write",
    "append",
    "read_ea",
    "write_ea",
    "execute",
    "delete_child",
    "read_attributes",
    "write_attributes",
    "delete",
    "read_control",
    "write_dac",
    "write_owner",
    "synchronize",
    "system_security"
  ],
  "share_permission": [
    "read",
    "read_ea",
    "execute",
    "read_attributes",
    "read_control",
    "synchronize"
  ]
}
----