---
sidebar: sidebar 
permalink: workflows/wf_stor_list_disks.html 
keywords: workflow, storage, disks, list disks 
summary: 'Vous pouvez récupérer la liste des disques du cluster. Vous pouvez ainsi localiser une ou plusieurs réserves à utiliser dans le cadre de la création d"un agrégat.' 
---
= Répertoriez les disques
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Vous pouvez récupérer la liste des disques du cluster. Vous pouvez ainsi localiser une ou plusieurs réserves à utiliser dans le cadre de la création d'un agrégat.

.Méthode HTTP et noeud final
Cet appel d'API REST utilise la méthode et le point de terminaison suivants.

[cols="25,75"]
|===
| Méthode HTTP | Chemin 


| OBTENEZ | /api/stockage/disques 
|===
.Type de traitement
Synchrone

.Paramètres d'entrée supplémentaires pour les exemples Curl
Outre les paramètres communs à tous les appels API REST, les paramètres suivants sont également utilisés dans les exemples de boucles pour cette étape.

[cols="25,10,10,55"]
|===
| Paramètre | Type | Obligatoire | Description 


| état | Requête | Non | Peut être utilisé pour identifier les disques de spare disponibles pour les nouveaux agrégats. 
|===
.Exemple curl : renvoie tous les disques
[source, curl]
----
curl --request GET \
--location "https://$FQDN_IP/api/storage/disks" \
--include \
--header "Accept: */*" \
--header "Authorization: Basic $BASIC_AUTH"
----
.Exemple curl : renvoyez les disques de rechange
[source, curl]
----
curl --request GET \
--location "https://$FQDN_IP/api/storage/disks?state=spare" \
--include \
--header "Accept: */*" \
--header "Authorization: Basic $BASIC_AUTH"
----
.Exemple de sortie JSON
[%collapsible]
====
[listing]
----
{
  "records": [
    {
      "name": "NET-1.20",
      "state": "spare",
      "_links": {
        "self": {
          "href": "/api/storage/disks/NET-1.20"
        }
      }
    },
    {
      "name": "NET-1.12",
      "state": "spare",
      "_links": {
        "self": {
          "href": "/api/storage/disks/NET-1.12"
        }
      }
    },
    {
      "name": "NET-1.7",
      "state": "spare",
      "_links": {
        "self": {
          "href": "/api/storage/disks/NET-1.7"
        }
      }
    }
  ],
  "num_records": 3,
  "_links": {
    "self": {
      "href": "/api/storage/disks?state=spare"
    }
  }
}
----
====