---
sidebar: sidebar 
permalink: workflows/wf_stor_list_aggrs.html 
keywords: workflow, storage, aggregates, list aggregates 
summary:  
---
= Lister les agrégats
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Vous pouvez récupérer la liste des agrégats dans le cluster. Vous pourriez le faire pour évaluer l'utilisation et les performances.

.Méthode HTTP et noeud final
Cet appel d'API REST utilise la méthode et le point de terminaison suivants.

[cols="25,75"]
|===
| Méthode HTTP | Chemin 


| OBTENEZ | /api/stockage/disques 
|===
.Type de traitement
Synchrone

.Paramètres d'entrée supplémentaires pour les exemples Curl
Outre les paramètres communs à tous les appels API REST, les paramètres suivants sont également utilisés dans les exemples de boucles pour cette étape.

[cols="25,10,10,55"]
|===
| Paramètre | Type | Obligatoire | Description 


| node.name | Requête | Non | Peut être utilisé pour identifier le nœud auquel chaque agrégat est rattaché. 
|===
.Exemple de bouclage : renvoie tous les agrégats avec les valeurs de configuration par défaut
[source, curl]
----
curl --request GET \
--location "https://$FQDN_IP/api/storage/aggregates" \
--include \
--header "Accept: */*" \
--header "Authorization: Basic $BASIC_AUTH"
----
.Exemple de bouclage : renvoie tous les agrégats avec une valeur de configuration spécifique
[source, curl]
----
curl --request GET \
--location "https://$FQDN_IP/api/storage/aggregates?fields=node.name" \
--include \
--header "Accept: */*" \
--header "Authorization: Basic $BASIC_AUTH"
----
.Exemple de sortie JSON
[%collapsible]
====
[listing]
----
{
  "records": [
    {
      "uuid": "760d8137-fc59-47da-906a-cc28db0a1c1b",
      "name": "sti214_vsim_sr027o_aggr1",
      "node": {
        "name": "sti214-vsim-sr027o"
      },
      "_links": {
        "self": {
          "href": "/api/storage/aggregates/760d8137-fc59-47da-906a-cc28db0a1c1b"
        }
      }
    }
  ],
  "num_records": 1,
  "_links": {
    "self": {
      "href": "/api/storage/aggregates?fields=node.name"
    }
  }
}
----
====