---
sidebar: sidebar 
permalink: python/prepare_pcl.html 
keywords: python client library, prepare, pcl 
summary: 'Vous devez préparer l"environnement d"exécution local avant d"utiliser la bibliothèque client Python.' 
---
= Préparez-vous à utiliser la bibliothèque client Python
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Vous devez préparer l'environnement d'exécution local avant d'utiliser la bibliothèque client Python.

.Nom et version du package
Le nom du pack de bibliothèque client Python est *netapp-ontap*. La version associée au package est une combinaison des numéros de version majeure et secondaire ONTAP à partir de laquelle la bibliothèque a été générée, avec une version mineure pour le client dans la version ONTAP. Par exemple, les numéros de version valides incluent : 9.6.1, 9.6.2 et 9.7.1.

.Installation
vous devez utiliser pip pour installer le package netapp_ontap à partir du site Web Python Package Index (PyPi).

.Packages et documentation par version de ONTAP
Chaque version de ONTAP commençant par 9.6 est dotée d'un progiciel PyPI et de la documentation associée. Voir link:../python/packages.html["Packages et documentation"] pour en savoir plus. Les exigences d'installation sont incluses avec chaque package et incluent différentes versions des éléments suivants :

* python
* demandes
* requêtes-courroie d'outils
* guimauve

