---
sidebar: sidebar 
permalink: get-started/access_rest_api.html 
keywords: access rest api, lif, cluster lif, svm lif, node lif 
summary: 'Vous pouvez accéder ONTAP à l"API REST de plusieurs façons.' 
---
= Comment accéder à l'API REST de ONTAP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Vous pouvez accéder ONTAP à l'API REST de plusieurs façons.



== Considérations réseau

Vous pouvez vous connecter à l'API REST ONTAP en utilisant l'un des nombreux types d'interfaces. L'interface LIF que vous choisissez doit être configurée pour prendre en charge le protocole de gestion HTTPS. De plus, la configuration du pare-feu de votre réseau doit autoriser le trafic HTTPS. Les interfaces suivantes sont prises en charge :

* LIF Cluster-management
* FRV de gestion des nœuds
* LIF de gestion SVM


Bien que vous puissiez utiliser n'importe laquelle de ces LIF, la meilleure pratique recommandée consiste à utiliser la LIF de gestion de cluster. Cela permet de considérer le cluster comme une seule unité logique et offre le plus haut niveau de résilience et d'équilibrage de charge. Un LIF de cluster peut se déplacer au sein du cluster selon les besoins pour gérer les mises à niveau planifiées, les événements de quorum et autres problèmes de connectivité. Si vous avez configuré plusieurs LIF de gestion de cluster, elles sont toutes équivalentes en ce qui concerne l'accès à l'API REST. Les LIF de gestion SVM sont également équilibrées en charge, mais les requêtes envoyées aux LIF limitées au niveau du nœud sont traitées localement.



== Page de documentation en ligne de l'API ONTAP

La page de documentation en ligne de l'API ONTAP fournit un point d'accès lors de l'utilisation d'un navigateur Web. En plus de fournir un moyen d'exécuter directement des appels API individuels, la page comprend une description détaillée de l'API, y compris les paramètres d'entrée et d'autres options pour chaque appel. Les appels API sont organisés en catégories fonctionnelles. Voir link:../resources/overview_categories.html["Résumé des ressources REST"] pour en savoir plus.

Le format de l'URL utilisé pour accéder à la page de documentation de la version la plus récente de l'API est :

`\https://<cluster_mgmt_ip_address>/docs/api`



== Logiciels et outils personnalisés

Vous pouvez accéder à l'API ONTAP à l'aide de plusieurs langages et outils de programmation différents. Il s'agit généralement de Python, Java, Curl et PowerShell. Un programme, un script ou un outil qui utilise l'API agit comme un client de services Web REST. L'utilisation d'un langage de programmation permet une compréhension plus approfondie de l'API et offre une opportunité d'automatiser l'administration de ONTAP.

Le format de l'URL de base utilisé pour accéder directement à la version la plus récente de l'API est :

`\https://<cluster_mgmt_ip_address>/api`

Pour accéder à une version API spécifique où plusieurs versions sont prises en charge, le format de l'URL est le suivant :

`\https://<cluster_mgmt_ip_address>/api/v1`
