---
sidebar: sidebar 
permalink: get-started/first_call.html 
keywords: first REST API call, test REST API 
summary: 'Vous pouvez exécuter une commande curl pour commencer à utiliser l"API REST ONTAP et confirmer sa disponibilité.' 
---
= Votre premier appel API
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Vous pouvez lancer une commande curl simple pour commencer à utiliser l'API REST de ONTAP et confirmer sa disponibilité.

.Avant de commencer
En plus de disposer de l'utilitaire curl sur votre poste de travail, vous avez besoin des éléments suivants :

* Adresse IP ou FQDN de la LIF de gestion de cluster ONTAP
* Identifiants ONTAP pour un compte habilité à accéder à l'API REST ONTAP



NOTE: Si vos informations d'identification incluent des caractères spéciaux, vous devez les formater d'une manière acceptable pour boucler en fonction du shell que vous utilisez. Par exemple, vous pouvez insérer une barre oblique inverse avant chaque caractère spécial ou envelopper la chaîne d'informations d'identification entière entre guillemets.

.Étapes
. Sur l'interface de ligne de commande de votre poste de travail local, exécutez la commande suivante :
+
[source, curl]
----
curl --request GET \
--user username:password \
"https://$FQDN_IP/api/cluster?fields=version"
----
+
*Exemple*

+
`curl --request GET --user admin:david123 "https://10.222.81.101/api/cluster?fields=version"`



.Une fois que vous avez terminé
Les informations relatives à la version de ONTAP sont affichées au format JSON.
