---
sidebar: sidebar 
permalink: get-started/ontap_automation_options.html 
keywords: ontap automation, rest api, python client library, powershell, ansible, bluexp automation catalog, netapp, console, hub 
summary: 'Plusieurs options sont disponibles pour automatiser le déploiement et l"administration de vos systèmes de stockage ONTAP.' 
---
= Découvrez les options d'automatisation ONTAP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Plusieurs options sont disponibles pour automatiser le déploiement et l'administration de vos systèmes de stockage ONTAP.



== L'API REST DE ONTAP

À partir d' ONTAP 9.6, ONTAP inclut une API REST robuste qui fournit la base pour automatiser le déploiement et l'administration de vos systèmes de stockage.  Depuis lors, l’API REST a continué à se développer et à mûrir.  Il fournit désormais l’option privilégiée et stratégique lors de l’automatisation de l’administration de vos déploiements ONTAP .

.Accès natif à l'API REST
Vous pouvez accéder directement à l'API REST de ONTAP via n'importe quel langage de programmation qui prend en charge un client REST. Il s'agit de Python, PowerShell et Java.

.Migration du code ONTAPI existant pour utiliser REST
L'API ONTAPI (Zephyr API ou ZAPI) est l'ensemble d'appels propriétaires d'origine inclus avec le logiciel NetApp ONTAP pour prendre en charge l'automatisation de vos tâches d'administration et de gestion du stockage de données.  L'API fait partie de lalink:../sw-tools/learn-about-nmsdk.html["SDK de gestion NetApp"] .  Si vous disposez d'un code existant utilisant l'API ONTAPI, vous devez planifier votre migration vers l'API REST ONTAP pour profiter de l'ensemble de fonctionnalités étendu disponible avec l'API REST.  NetApp fournit une assistance pour la conversion de votre code afin d'utiliser la nouvelle API REST ONTAP . Voir link:../migrate/migration-considerations.html["Migration d'ONTAPI vers l'API REST"] pour plus d'informations.



== Kits d'outils logiciels client

NetApp propose des kits d'outils client qui extraient l'API REST ONTAP et facilitent la création du code d'automatisation. Vous devez en choisir un adapté à votre langue et à votre environnement de développement.

.Bibliothèque client Python
La bibliothèque client Python est un pack que vous pouvez utiliser lors de l'écriture de scripts pour accéder à l'API REST de ONTAP. Il prend en charge plusieurs services sous-jacents, notamment la gestion des connexions, le traitement asynchrone des demandes et le traitement des exceptions. Il vous suffit d'utiliser la bibliothèque client Python pour développer rapidement un code robuste en vue de la prise en charge de vos objectifs en matière d'automatisation ONTAP. Voir link:../python/learn-about-pcl.html["Bibliothèque client Python"] pour plus d'informations.

.Kit PowerShell
Vous pouvez utiliser le kit NetApp.ONTAP PowerShell pour automatiser l'administration d'un cluster ONTAP à partir d'un hôte Windows. Voir link:../pstk/learn-about-pstk.html["En savoir plus sur le kit NetApp PowerShell"] pour plus d'informations.



== Frameworks d'automatisation

Vous pouvez créer et déployer du code d’automatisation à l’aide de plusieurs frameworks.

.Ansible
Ansible est un outil logiciel open source qui prend en charge le provisionnement, la gestion de la configuration et le déploiement d'applications. Depuis sa sortie et son acquisition ultérieure par RedHat, elle a continué de croître dans la popularité. NetApp fournit des modules certifiés Ansible qui permettent aux clients d'automatiser l'administration de leurs systèmes de stockage ONTAP. Voir link:../additional/learn_more.html["En savoir plus >>"] et https://www.netapp.com/devops-solutions/ansible/["Solutions DevOps NetApp Ansible"^] pour plus d'informations.

.Centre d'automatisation NetApp Console
Le https://console.netapp.com/automationHub["Centre d'automatisation NetApp Console"^] est disponible via l'interface utilisateur Web de la console. La plateforme d'automatisation donne accès à des solutions packagées qui peuvent vous aider à automatiser le déploiement et l'intégration d' ONTAP avec d'autres produits. Voir https://docs.netapp.com/us-en/netapp-automation/["Automatisation NetApp"^] pour la documentation et plus d'informations.
