---
sidebar: sidebar 
permalink: rest/access_ontap_cli.html 
keywords: cli, ontap cli, cli passthrough 
summary: 'Pour aider les utilisateurs de l"interface de ligne de commande et de l"API ONTAPI lors de la transition vers l"API REST ONTAP, ONTAP fournit un terminal REST pour accéder à l"interface de ligne de commandes. Vous pouvez utiliser cette fonctionnalité de passe-système pour exécuter n"importe quelle commande CLI.' 
---
= Accès à l'interface de ligne de commandes de ONTAP via l'API REST
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Pour aider les utilisateurs de l'interface de ligne de commande et de l'API ONTAPI lors de la transition vers l'API REST ONTAP, ONTAP fournit un terminal REST pour accéder à l'interface de ligne de commandes. Vous pouvez utiliser cette fonctionnalité de passe-système pour exécuter n'importe quelle commande CLI. L'utilisation du terminal REST est renvoyée dans les données AutoSupport pour que NetApp puisse identifier des lacunes dans l'API REST et apporter des améliorations dans les versions ultérieures.

Pour lancer une commande CLI, vous devez effectuer un appel d'API REST correctement formé, en fonction des règles relatives à :

* Chemins de ressources
* Noms de champ
* Méthodes HTTP


Le chemin des ressources de base pour l'accès à l'interface de ligne de commande est `/private/cli`. Pour plus d'informations sur l'accès à l'interface de ligne de commandes via l'API REST, consultez la page de documentation en ligne de l'API ONTAP.


NOTE: NetApp tient à jour un référentiel GitHub contenant des exemples de code et d'autres informations utiles. Vous pouvez accéder au référentiel pour obtenir des exemples d'utilisation de la fonction d'authentification CLI.

https://github.com/NetApp/ontap-rest-python/tree/master/examples/rest_api/cli_passthrough_samples["Référentiel Python REST de ONTAP : exemples de passerelle CLI"^]
