---
sidebar: sidebar 
permalink: rest/access_rest_api.html 
keywords: accessing the rest api, lif 
summary: 'Vous pouvez accéder ONTAP à l"API REST de plusieurs façons.' 
---
= Comment accéder à l'API REST de ONTAP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Vous pouvez accéder ONTAP à l'API REST de plusieurs façons.



== Considérations réseau

Vous pouvez vous connecter à l'API REST via les interfaces suivantes :

* LIF Cluster-management
* FRV de gestion des nœuds
* LIF de gestion SVM


La LIF que vous choisissez d'utiliser doit être configurée pour prendre en charge le protocole de gestion HTTPS. De plus, la configuration du pare-feu de votre réseau doit autoriser le trafic HTTPS.


TIP: Vous devez toujours utiliser une LIF de cluster management. La charge sera ainsi équilibrée entre les requêtes d'API sur tous les nœuds et évitez les nœuds hors ligne ou qui rencontrent des problèmes de connectivité. Si plusieurs LIF de cluster management sont configurées, elles sont toutes équivalentes en ce qui concerne l'accès à l'API REST.



== Page de documentation en ligne de l'API ONTAP

La page de documentation en ligne de l'API ONTAP fournit un point d'accès lors de l'utilisation d'un navigateur Web. En plus de fournir un moyen d'exécuter directement des appels API individuels, la page comprend une description détaillée de l'API, y compris les paramètres d'entrée et d'autres options pour chaque appel. Les appels API sont organisés en catégories fonctionnelles. Voir link:../resources/overview_categories.html["Résumé des ressources REST"] pour en savoir plus.

Le format de l'URL utilisé pour accéder à la page de documentation de la version la plus récente de l'API est :

`https://<cluster_mgmt_ip_address>/docs/api`



== Logiciels et outils personnalisés

Vous pouvez accéder à l'API ONTAP à l'aide de plusieurs langages et outils de programmation différents. Il s'agit généralement de Python, Java, Curl et PowerShell. Un programme, un script ou un outil qui utilise l'API agit comme un client de services Web REST. L'utilisation d'un langage de programmation permet une compréhension plus approfondie de l'API et offre une opportunité d'automatiser l'administration de ONTAP.

Le format de l'URL de base utilisé pour accéder directement à la version la plus récente de l'API est :

`https://<cluster_mgmt_ip_address>/api`

Pour accéder à une version API spécifique où plusieurs versions sont prises en charge, le format de l'URL est le suivant :

`https://<cluster_mgmt_ip_address>/api/v1`
