---
sidebar: sidebar 
permalink: rest/rbac_sample_roles.html 
keywords: rbac, role definitions, samples 
summary: 'Selon l"environnement, la fonctionnalité RBAC de ONTAP peut être utilisée de différentes manières. Voici quelques scénarios courants. Dans chaque cas, l"accent est mis sur un objectif spécifique de sécurité et d"administration avec un exemple de définition de rôle correspondante.' 
---
= Exemples de définitions de rôle
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Selon l'environnement, la fonctionnalité RBAC de ONTAP peut être utilisée de différentes manières. Voici quelques scénarios courants. Dans chaque cas, l'accent est mis sur un objectif spécifique de sécurité et d'administration avec un exemple de définition de rôle correspondante.


NOTE: Tous les exemples créent et modifient des rôles à l'aide de `/api/security/roles` Et les extrémités REST dérivées. Pour plus de clarté, chaque commande curl fait référence à un fichier d'entrée JSON distinct.



== Limiter l'accès aux opérations de volume du SVM

Vous pouvez limiter l'administration des volumes de stockage au sein d'une SVM. L'exemple ci-dessous illustre ce rôle avec un rôle créé en premier puis mis à jour en option.



=== Créer le rôle initial

Un rôle traditionnel est créé pour permettre au départ l'accès à toutes les principales fonctions d'administration de volume, à l'exception du clonage. Le rôle présenté ci-dessous est défini avec les caractéristiques spécifiques suivantes :

* Possibilité d'effectuer toutes les opérations de volume CRUD, y compris obtenir, créer, modifier et supprimer
* Impossible de créer un clone de volume


.exemple de boucle
[source, curl]
----
curl --location -i --request POST 'https://10.63.56.136/api/security/roles' -u admin:password -k --header 'Accept: */*' --data @JSONinput
----
.Exemple d'entrée JSON
[source, json]
----
{
  "name": "role1",
  "owner": {
    "name": "cluster-1",
    "uuid": "852d96be-f17c-11ec-9d19-005056bbad91"
  },
  "privileges": [
      { "path": "volume create", "access": "all" },
      { "path": "volume delete", "access": "all" }
    ]
}
----


=== Mettre à jour le rôle

Le rôle peut être modifié afin de permettre à l'utilisateur de créer également un clone de volume.

.exemple de boucle
[source, curl]
----
curl --location -i --request POST 'https://10.63.56.136/api/security/roles/852d96be-f17c-11ec-9d19-005056bbad91/role1/privileges' -u admin:password -k --header 'Accept: */*' --data @JSONinput
----
.Exemple d'entrée JSON
[source, json]
----
{
  "path": "volume clone",
  "access": "all"
}
----


== Administration de la protection des données

Dans certains cas, vous pouvez fournir à un utilisateur des capacités de protection des données limitées. Le rôle traditionnel présenté ci-dessous est défini avec les caractéristiques suivantes :

* Création et suppression de snapshots et mise à jour des relations SnapMirror
* Ne peut créer ou modifier des objets de niveau supérieur tels que des volumes ou des SVM


.exemple de boucle
[source, curl]
----
curl --location -i --request POST 'https://10.63.56.136/api/security/roles' -u admin:password -k --header 'Accept: */*' --data @JSONinput
----
.Exemple d'entrée JSON
[source, json]
----
{
  "name": "role1",
  "owner": {
    "name": "cluster-1",
    "uuid": "852d96be-f17c-11ec-9d19-005056bbad91"
  },
  "privileges": [
      {"path": "volume snapshot create", "access": "all"},
      {"path": "volume snapshot delete", "access": "all"},
      {"path": "volume show", "access": "readonly"},
      {"path": "vserver show", "access": "readonly"},
      {"path": "snapmirror show", "access": "readonly"},
      {"path": "snapmirror update", "access": "all"}
  ]
}
----


== Génération de rapports ONTAP

Vous pouvez créer un rôle REST pour permettre aux utilisateurs de générer des rapports ONTAP. Le rôle présenté ci-dessous est défini avec les caractéristiques suivantes :

* Possibilité de récupérer toutes les informations relatives à la capacité et aux performances de l'objet de stockage (par exemple, volume, qtree, LUN, agrégats, nœud, Et relations SnapMirror)
* Ne peut créer ni modifier des objets de niveau supérieur (tels que des volumes ou des SVM)


.exemple de boucle
[source, curl]
----
curl --location -i --request POST 'https://10.63.56.136/api/security/roles' -u admin:password -k --header 'Accept: */*' --data @JSONinput
----
.Exemple d'entrée JSON
[source, json]
----
{
  "name": "rest_role1",
  "owner": {
    "name": "cluster-1",
    "uuid": "852d96be-f17c-11ec-9d19-005056bbad91"
  },
  "privileges": [
      {"path": "/api/storage/volumes", "access": "readonly"},
      {"path": "/api/storage/qtrees", "access": "readonly"},
      {"path": "/api/storage/luns", "access": "readonly"},
      {"path": "/api/storage/aggregates", "access": "readonly"},
      {"path": "/api/cluster/nodes", "access": "readonly"},
      {"path": "/api/snapmirror/relationships", "access": "readonly"},
      {"path": "/api/svm/svms", "access": "readonly"}
  ]
}
----