---
sidebar: sidebar 
permalink: rest/users_ontapi_api_ontap_cli.html 
keywords: snapdiff, migrating to rest 
summary: 'ONTAPI est un ensemble d"appels d"API fournis via le SDK de gestion réseau qui peut être utilisé pour gérer les systèmes de stockage ONTAP. Il existe des différences entre les appels de l"API REST et de l"API ONTAPI, ainsi qu"entre l"API REST et l"interface de ligne de commande ONTAP.' 
---
= Utilisateurs de l'API ONTAPI et de l'interface de ligne de commande ONTAP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
ONTAPI est un ensemble d'appels d'API fournis via le SDK de gestion réseau qui peut être utilisé pour gérer les systèmes de stockage ONTAP. Il existe des différences entre les appels de l'API REST et de l'API ONTAPI, ainsi qu'entre l'API REST et l'interface de ligne de commande ONTAP. Vous devez comprendre ces différences avant d'utiliser l'API REST dans un environnement de production.



== Différences générales de conception

L'API REST et l'interface de ligne de commande de ONTAP ont des conceptions radicalement différentes. Les commandes et paramètres de la CLI ne sont pas directement associés aux appels de l'API REST. Et même lorsqu'il peut y avoir une similarité, les détails des paramètres d'entrée peuvent être différents. Par exemple, des unités numériques peuvent être spécifiées en octets ou à l'aide d'un suffixe (comme Ko). Vous devriez passer en revue link:input_variables.html["Variables d'entrée contrôlant une requête API"] ainsi que le link:../reference/api_reference.html["Référence API"] pour en savoir plus.



== Les SVM de données exposés via l'API REST

ONTAP prend en charge plusieurs types de serveurs virtuels de stockage (SVM). Toutefois, seuls les SVM de données sont directement exposés via l'API REST de ONTAP. Les informations de configuration décrivant le cluster et les nœuds sont disponibles via l'API REST, mais le cluster et les nœuds ne sont pas traités comme des SVM distincts.



== Migration depuis ONTAPI vers REPOS

L'API REST est le choix principal et stratégique pour automatiser l'administration du système ONTAP. Si vous utilisez actuellement l'API ONTAPI, vous devez envisager de migrer vers l'API REST. NetApp fournit une documentation relative au mappage afin d'assister la migration de ONTAPI vers LE REPOS. Voir link:../migrate/mapping.html["Mappage de l'API REST avec ONTAPI"] pour en savoir plus.



== Modifications de la disponibilité SnapDiff dans ONTAPI

Depuis ONTAP 9.10.1, les appels SnapDiff v1 et v2 ONTAPI ne peuvent pas être appelés. Toute application tierce qui appelle les appels ONTAPI SnapDiff v1 ou v2 ne fonctionnera pas avec ONTAP 9.10.1. Les utilisateurs de ONTAP doivent vérifier que leur application de sauvegarde prend en charge les appels REST SnapDiff v3 avant de passer à ONTAP 9.10.1.

La disponibilité de l'API SnapDiff sur les versions ONTAP est définie comme suit :

* ONTAP 9.7 et versions antérieures : v1 et v2 (ONTAPI uniquement)
* ONTAP 9.8 – 9.9 : v1, v2 et v3 (API ONTAPI et REST)
* ONTAP 9.10.1 : v3 uniquement (API REST uniquement)


Pour plus d'informations, reportez-vous à la section https://library.netapp.com/ecm/ecm_download_file/ECMLP2492508["Notes de version de ONTAP"^].

.Informations associées
* link:../rest/input_variables.html["Variables d'entrée contrôlant une requête API"]
* link:../migrate/mapping.html["Mappage de l'API REST avec ONTAPI"]

