---
permalink: manage/dacl-sacl-rest-api.html 
sidebar: sidebar 
keywords: dacl, sacl, permissions, file, api, access, vserver, control, list, access control list, access control 
summary: 'Vous pouvez gérer les autorisations DACL et SACL à l"aide de l"API REST de ONTAP.' 
---
= Gérez les autorisations d'accès aux fichiers DACL et SACL avec l'API REST de ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP utilise les listes de contrôle d'accès système (CLS) et les listes de contrôle d'accès discrétionnaire (listes ACL) pour attribuer des autorisations aux objets de fichier. Depuis ONTAP 9.9.1, l'API REST de ONTAP inclut des terminaux pour attribuer des autorisations SACL et DACL aux fichiers et automatiser les autorisations de sécurité des fichiers. (Pour en savoir plus sur les options d'automatisation des autorisations SACL et DACL avant ONTAP 9.9.1 https://netapp.io/2020/11/09/private-cli-passthrough-ontap-rest-api/["ici"^]).

Depuis la version ONTAP 9.9.1, vous pouvez utiliser un seul appel d'API REST à la place de plusieurs commandes d'interface de ligne de commande ou appels ONTAPI. Les exemples suivants montrent comment utiliser l'API REST de ONTAP pour travailler avec les autorisations de fichiers. Dans chaque exemple, veillez à fournir les valeurs pour les informations entre parenthèses <> à la place indiquée.

Vous pouvez également référencer un échantillon https://github.com/NetApp/ontap-rest-python/blob/master/examples/rest_api/file_security_permissions.py["Script Python"^] Cela explique comment automatiser un certain nombre d'activités liées à la SACL et à la DACL.



== Afficher les autorisations effectives

À l'aide du `GET /protocols/file-security/effective-permissions/` Appel d'API, vous pouvez récupérer les autorisations en cours pour un fichier ou un répertoire spécifique.

.Exemple de demande :
[source, curl]
----
curl -X GET -u admin:<PASSWORD> -k 'https://<IP_ADDRESS>/api/protocols/file-security/effective-permissions/cf5f271a-1beb-11ea-8fad-005056bb645e/administrator/windows/%2F?share.name=sh1&return_records=true'
----
.Exemple de réponse
[source, json]
----
{
  "svm": {
    "uuid": "cf5f271a-1beb-11ea-8fad-005056bb645e",
    "name": "vs1"
  },
  "user": "administrator",
  "type": "windows",
  "path": "/",
  "share": {
    "path": "/"
  },
  "file_permission": [
    "read",
    "write",
    "append",
    "read_ea",
    "write_ea",
    "execute",
    "delete_child",
    "read_attributes",
    "write_attributes",
    "delete",
    "read_control",
    "write_dac",
    "write_owner",
    "synchronize",
    "system_security"
  ],
  "share_permission": [
    "read",
    "read_ea",
    "execute",
    "read_attributes",
    "read_control",
    "synchronize"
  ]
}
----


== Afficher toutes les informations d'audit

À l'aide du `GET /protocols/file-security/permissions/` Appel API : vous pouvez récupérer toutes les informations d'audit d'un fichier ou d'un répertoire spécifique.

.Exemple de demande :
[source, curl]
----
curl -X GET -u admin:<PASSWORD> -k 'https://<IP_ADDRESS>/api/protocols/file-security/permissions/9479099d-5b9f-11eb-9c4e-0050568e8682/%2Fparent'
----
.Exemple de réponse
[source, json]
----
{
  "svm": {
    "uuid": "9479099d-5b9f-11eb-9c4e-0050568e8682",
    "name": "vs1"
  },
  "path": "/parent",
  "owner": "BUILTIN\\Administrators",
  "group": "BUILTIN\\Administrators",
  "control_flags": "0x8014",
  "acls": [
    {
      "user": "BUILTIN\\Administrators",
      "access": "access_allow",
      "apply_to": {
        "files": true,
        "sub_folders": true,
        "this_folder": true
      },
      "advanced_rights": {
        "append_data": true,
        "delete": true,
        "delete_child": true,
        "execute_file": true,
        "full_control": true,
        "read_attr": true,
        "read_data": true,
        "read_ea": true,
        "read_perm": true,
        "write_attr": true,
        "write_data": true,
        "write_ea": true,
        "write_owner": true,
        "synchronize": true,
        "write_perm": true
      },
      "access_control": "file_directory"
    },
    {
      "user": "BUILTIN\\Users",
      "access": "access_allow",
      "apply_to": {
        "files": true,
        "sub_folders": true,
        "this_folder": true
      },
      "advanced_rights": {
        "append_data": true,
        "delete": true,
        "delete_child": true,
        "execute_file": true,
        "full_control": true,
        "read_attr": true,
        "read_data": true,
        "read_ea": true,
        "read_perm": true,
        "write_attr": true,
        "write_data": true,
        "write_ea": true,
        "write_owner": true,
        "synchronize": true,
        "write_perm": true
      },
      "access_control": "file_directory"
    }
  ],
  "inode": 64,
  "security_style": "mixed",
  "effective_style": "ntfs",
  "dos_attributes": "10",
  "text_dos_attr": "----D---",
  "user_id": "0",
  "group_id": "0",
  "mode_bits": 777,
  "text_mode_bits": "rwxrwxrwx"
}

----


== Appliquer de nouvelles autorisations

À l'aide du `POST /protocols/file-security/permissions/` Appel API, vous pouvez appliquer un nouveau descripteur de sécurité à un fichier ou à un répertoire.

.Exemple de demande
[source, curl]
----
curl -u admin:<PASSWORD> -X POST -d '{ \"acls\": [ { \"access\": \"access_allow\", \"advanced_rights\": { \"append_data\": true, \"delete\": true, \"delete_child\": true, \"execute_file\": true, \"full_control\": true, \"read_attr\": true, \"read_data\": true, \"read_ea\": true, \"read_perm\": true, \"write_attr\": true, \"write_data\": true, \"write_ea\": true, \"write_owner\": true, \"write_perm\": true }, \"apply_to\": { \"files\": true, \"sub_folders\": true, \"this_folder\": true }, \"user\": \"administrator\" } ], \"control_flags\": \"32788\", \"group\": \"S-1-5-21-2233347455-2266964949-1780268902-69700\", \"ignore_paths\": [ \"/parent/child2\" ], \"owner\": \"S-1-5-21-2233347455-2266964949-1780268902-69304\", \"propagation_mode\": \"propagate\"}' -k 'https://<IP_ADDRESS>/api/protocols/file-security/permissions/9479099d-5b9f-11eb-9c4e-0050568e8682/%2Fparent?return_timeout=0'
----
.Exemple de réponse
[source, json]
----
{
  "job": {
    "uuid": "3015c294-5bbc-11eb-9c4e-0050568e8682",
    "_links": {
      "self": {
        "href": "/api/cluster/jobs/3015c294-5bbc-11eb-9c4e-0050568e8682"
      }
    }
  }
}
----


== Mettez à jour les informations du descripteur de sécurité

À l'aide du `PATCH /protocols/file-security/permissions/` Appel API : vous pouvez mettre à jour des informations de descripteur de sécurité spécifiques pour un fichier ou un répertoire, telles que le propriétaire principal, le groupe ou les indicateurs de contrôle.

.Exemple de demande
[source, curl]
----
curl -u admin:<PASSWORD> -X PATCH -d '{ \"control_flags\": \"32788\", \"group\": \"everyone\", \"owner\": \"user1\"}' -k 'https://<IP_ADDRESS>/api/protocols/file-security/permissions/9479099d-5b9f-11eb-9c4e-0050568e8682/%2Fparent?return_timeout=0'
----
.Exemple de réponse
[source, json]
----
{
  "job": {
    "uuid": "6f89e612-5bbd-11eb-9c4e-0050568e8682",
    "_links": {
      "self": {
        "href": "/api/cluster/jobs/6f89e612-5bbd-11eb-9c4e-0050568e8682"
      }
    }
  }
}
----


== Supprimer une entrée de contrôle d'accès (ACE) SACL/DACL existante

À l'aide du `DELETE /protocols/file-security/permissions/` Appel API : vous pouvez supprimer une ACE existante d'un fichier pour répertoire. Cet exemple propage la modification à n'importe quel objet enfant.

.Exemple de demande
[source, curl]
----
curl -u admin:<PASSWORD> -X DELETE -d '{ \"access\": \"access_allow\", \"apply_to\": { \"files\": true, \"sub_folders\": true, \"this_folder\": true }, \"ignore_paths\": [ \"/parent/child2\" ], \"propagation_mode\": \"propagate\"}' -k 'https://<IP_ADDRESS>/api/protocols/file-security/permissions/9479099d-5b9f-11eb-9c4e-0050568e8682/%2Fparent/acl/himanshu?return_timeout=0'
----
.Exemple de réponse
[source, json]
----
{
  "job": {
    "uuid": "e5683b61-5bbf-11eb-9c4e-0050568e8682",
    "_links": {
      "self": {
        "href": "/api/cluster/jobs/e5683b61-5bbf-11eb-9c4e-0050568e8682"
      }
    }
  }
}
----


== Comparaison des commandes de l'API REST ONTAP et de l'interface CLI ONTAP

L'API REST de ONTAP vous permet d'automatiser les workflows avec moins de commandes que l'interface de ligne de commandes ONTAP pour de nombreuses tâches. Par exemple, vous pouvez utiliser une méthode POST API unique pour modifier un descripteur de sécurité pour un fichier, au lieu d'utiliser plusieurs commandes CLI. Le tableau suivant présente les commandes CLI dont vous aurez besoin pour effectuer les tâches courantes d'autorisation de système de fichiers par rapport aux appels de l'API REST correspondants :

|===
| L'API REST DE ONTAP | INTERFACE DE LIGNE DE COMMANDES DE ONTAP 


| `GET /protocols/file-security/effective-permissions/`  a| 
`vserver security file-directory show-effective-permissions`



| `POST /protocols/file-security/permissions/`  a| 
. `vserver security file-directory ntfs create`
. `vserver security file-directory ntfs dacl add`
. `vserver security file-directory ntfs sacl add`
. `vserver security file-directory policy create`
. `vserver security file-directory policy task add`
. `vserver security file-directory apply`




| `PATCH /protocols/file-security/permissions/`  a| 
`vserver security file-directory ntfs modify`



| `DELETE /protocols/file-security/permissions/`  a| 
. `vserver security file-directory ntfs dacl remove`
. `vserver security file-directory ntfs sacl remove`


|===


== Informations associées

* https://github.com/NetApp/ontap-rest-python/blob/master/examples/rest_api/file_security_permissions.py["Exemples d'autorisations DACL/SACL de l'API REST ONTAP exemple de script Python"^]
* https://netapp.io/2021/06/28/simplified-management-of-file-security-permissions-with-ontap-rest-apis/["Gestion simplifiée des autorisations de sécurité de fichiers avec les API REST ONTAP"^]
* https://netapp.io/2020/11/09/private-cli-passthrough-ontap-rest-api/["Utilisation de la passerelle d'interface de ligne de commande privée avec l'API REST ONTAP (pour les versions antérieures à la version 9.9 de ONTAP)"^]

